import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import AsideNav from '@/components/Aside'
import Header from '@/components/Header'
import FloatInfo from '@/components/FloatInfo'

const inter = Inter({ subsets: ['latin'] })
const popins = Poppins({subsets: ['latin'], weight:["400","500",'600','700' ]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={popins.className}>
        <nav className='main_nav_side'>
          <AsideNav/>
        </nav>
        <Header/>
        <div className='main_first'>
          {children}
        </div>
        <FloatInfo quantityVideo={4} program={5}/>
      </body>
    </html>
  )
}
